### ISSUE TITLE
Consider creating indexes for each table after it is loaded

### ISSUE THREAD

**Issue by jamesaoverton** [ontodev/valve.rs#15]
The received wisdom seems to be that it's better to load first and then index. Since we want our foreign key dependencies to be indexes, in our case we would want to index each table after its rows are inserted. We could also consider creating each table just before it is loaded, if that makes this change easier.

**Comment by jamesaoverton** [comment]
Before major refactoring, let's see if SQLite and Postgres have features for delaying index updates until the table is loaded.

**Comment by lmcmicu** [comment]
PostgreSQL allows one to disable indexes by setting the `indisready` field to false for a given index in the `pg_index` table: https://www.postgresql.org/docs/current/catalog-pg-index.html

I still need to check SQLite.

**Comment by lmcmicu** [comment]
In SQLite foreign key checks are controlled using the command `PRAGMA foreign_keys = <OFF|ON>`. It doesn't appear to be possible to disable other types of keys (though this seems possible in postgres, as per the above comment).

By default foreign keys are actually off in SQLite, and we are explicitly setting them to ON during load [at this line](https://github.com/ontodev/valve.rs/blob/5a1a8753b087f5f3f6b07f47f52b2754c5a3531c/src/lib.rs#L1910).

Note that regardless whether we (a) disable the keys or (b) create indexes after loading, there is one important part of the algorithm that will need to be changed. In particular there are places in the code where we use the "better to ask forgiveness than permission" strategy; i.e., we depend on a foreign key violation being triggered, and then only generate the errors corresponding to them (i.e. in the meta columns) when they are. For example (this might be the only example, see [here](https://github.com/ontodev/valve.rs/blob/5a1a8753b087f5f3f6b07f47f52b2754c5a3531c/src/lib.rs#L1042).

It isn't clear to me that the performance gain from disabling indexes (or deferring their creation) is worth not using the above trick, but it also isn't clear that it isn't worth it. It would probably be worth trying.

**Comment by lmcmicu** [comment]
Further info: PostgreSQL allows you to add a foreign key to an existing column of a given table after it is created, but SQLite does not seem to allow this. So I think that if we are going to try this optimization the right strategy should be something like the following:

Before load:
- Defer creation of unique indexes and primary keys
- Do not defer creation of foreign keys, but disable them.

After load:
- Add unique indexes and primary key constraints
- Enable foreign keys

**Comment by lmcmicu** [comment]
We'll shelve this for now.
