### ISSUE TITLE
Test performance of alternative schema

### ISSUE THREAD

**Issue by jamesaoverton** [ontodev/valve.rs#27]
For a large dataset I'm testing, exporting the 'message' table is quite slow. We're planning to add an 'update' table, which might be too slow for my goals. I want to experiment with an alternative schema that does not include _meta columns, but moves that information into a 'cell' table and a 'message' table. Building on #26, I want to see how the performance compares to our current schema.

For this experiment, I don't want to change the VALVE Rust code at all. I'm hoping that we can load the test data from #16 as normal, then write a bit of SQL/Python to copy our target table T to the new schema. Here's a sketch of the new schema.

`measurement.tsv` file:

| subject | mass (g)
|---|---
| N1A1 | 3750
| N1A2 |
|  | 3500

'measurement' SQL table:

rownum | subject | mass (g)
---|---|---
1 | N1A1 | 3750
2 | N1A2 | NULL

'measurement_conflict' table:

rownum | subject | mass (g)
---|---|---
3 | NULL | 3500

'measurement_view' view (maybe not needed for this):

rownum | subject | mass (g)
---|---|---
1 | N1A1 | 3750
2 | N1A2 | NULL
3 | NULL | 3500

**[EDIT: We've decided not to use the 'cell' table, at least for now.]**
The 'cell' table captures some of the keys from the meta column JSON, such as `valid` (when false):

table | row | column | nullvalue | valid
---|---|---|---|---
measurement | 2 | mass (g) | | FALSE
measurement | 3 | mass (g) | | FALSE

The 'nullvalue' is the string value of a cell that is represented by NULL.

The 'message' table captures the 'messages' key from the meta column JSON:

table | row | column | level | rule | message
---|---|---|---|---|---
measurement | 2 | mass (g) | error | required value | The 'mass (g)' column requires a value.
measurement | 3 | subject  | error | primary key    | The 'subject' column requires a value.

One of the design goals for the current schema was to keep it simple to query the data and get the metadata. With this approach I expect queries to be more complicated, but usually more performant. To get 100 rows (with some arbitrary offset) as JSON with cells, I think we need to:

1. `SELECT * FROM measurement_view LIMIT 100 OFFSET 12345` to get the row numbers
2. `SELECT * FROM cell WHERE row IN` those rows
3. `SELECT * FROM message WHERE rownum IN` those rows
4. merge these three into our JSON result

For the test in #26 asking for all rows with errors as JSON with cells, I think we end up running three queries:

1. `SELECT * FROM message WHERE table='measurement'` to get the row numbers
2. `SELECT * FROM measurement_view WHERE rownum IN` those rows
3. `SELECT * FROM cell WHERE row IN` those rows
4. merge these three into our JSON result

**Comment by lmcmicu** [comment]
I'm having a bit of trouble understanding the purpose of the `cell` table, which seems redundant. Given that we will only have a message if a value is invalid, why not merge `cell` and `message` into one table?

**Comment by jamesaoverton** [comment]
I agree that it’s currently redundant, so let’s skip it for now. I have a future use case in mind.

**Comment by lmcmicu** [comment]
I have hacked together a SQL script and a python script to create and load a few new tables conforming to this new schema. The tables are constructed (using the scripts) on the basis of `table2`, a table which conforms to the old schema.

The new tables are:
`table2_alt`
`table2_alt_conflict`
`cell`
`message`

You can see the way they are populated by having a look at the two scripts (which should be self-explanatory). I have not committed this code but am attaching the scripts to this comment, along with a copy of the sqlite database with the resulting tables inside. Note that I have gzipped the files because GitHub requires that a file have a supported extension to attach it to a comment.

[valve_perf.db.gz](https://github.com/ontodev/valve.rs/files/10148713/valve_perf.db.gz)
[alternate_schema.sql.gz](https://github.com/ontodev/valve.rs/files/10148716/alternate_schema.sql.gz)
[load_alternate_messages.py.gz](https://github.com/ontodev/valve.rs/files/10148717/load_alternate_messages.py.gz)

Please have a look and let me know if this is more or less what you are looking for with this new schema.

**Comment by lmcmicu** [comment]
On second thought I did commit those two scripts, here: https://github.com/ontodev/valve.rs/blob/perf-tests/test/perf_test_data/query_tests/alternate_schema.sql and here: https://github.com/ontodev/valve.rs/blob/perf-tests/test/perf_test_data/query_tests/load_alternate_messages.py

I did not commit the sqlite database, but it is still attached to the previous comment.

**Comment by lmcmicu** [comment]
After getting some feedback from @jamesaoverton about precisely what the contents of these tests should be, I produced the following Excel spreadsheet with the appropriate statistics. Note that some of the tests included here are related to #26 .
[Schema comparison.xlsx](https://github.com/ontodev/valve.rs/files/10201640/Schema.comparison.xlsx)

**Comment by lmcmicu** [comment]
After eliminating the `cell` table and using `union all` instead of `union` there is a vast improvement in performance. The new numbers are attached to this comment.
[Schema comparison.xlsx](https://github.com/ontodev/valve.rs/files/10210089/Schema.comparison.xlsx)

**Comment by lmcmicu** [comment]
I just realised that there is a problem with this schema. I think we need to add a `value` column to the `message` table, i.e.,
```
table | row | column | value | level | rule | message
```
Otherwise it will not be possible to round-trip, and it will also be impossible to have multiple validation failures per cell.
