### ISSUE TITLE
Weird problem with SQLite file path in export.py

### ISSUE THREAD

**Issue by jamesaoverton** [ontodev/valve.rs#30]
Running `make sqlite_test` I consistently get an error in `export.py`:

```console
Traceback (most recent call last):
  File "/home/knocean/valve.rs/test/../scripts/export.py", line 397, in <module>
    with sqlite3.connect(db) as conn:
sqlite3.OperationalError: unable to open database file
```

The problem is this line <https://github.com/ontodev/valve.rs/blob/main/scripts/export.py#L396>. If I remove the "file:" part, it works fine. This doesn't make sense to me, since it's obviously working on @lmcmicu's machine and the GitHub Actions. My setup is:

- `uname -a` `Linux dev 5.15.79 #1-NixOS SMP Wed Nov 16 08:58:31 UTC 2022 x86_64 GNU/Linux`
- Python 3.10.8
- Python `sqlite3.version` 2.6.0
- Python `sqlite3.sqlite_version` 3.39.4

@lmcmicu Is there any harm in changing that line to `db = f"{path}{params}"`?

**Comment by lmcmicu** [comment]
No there should be no harm, and I've tested it and it seems fine.

I'm not sure, but it's possible that this has something to do with the sqlite version. Mine is 3.34.1.
