### ISSUE TITLE
Implement `delete_row`

### ISSUE THREAD

**Issue by jamesaoverton** [ontodev/valve.rs#44]
This is basic functionality that turns out to be complicated... We need to:

1. check whether deleting the row breaks any foreign key constraints
2. delete any messages from the 'message' table? if we keep them, it will skew our message counts
3. delete the row itself

From a user perspective, I get very nervous about deleting stuff unless I know I can undo and redo, which VALVE does not yet support. That's even more complicated, so deserves its own issue.

**Comment by lmcmicu** [comment]
For the changes on the nanobot.rs side needed for this, see https://github.com/ontodev/nanobot.rs/pull/55
