### ISSUE TITLE
Possible bug: No messages generated with datatype lacks a description

### ISSUE THREAD

**Issue by jamesaoverton** [ontodev/valve.rs#50]
When the 'description' column of the 'datatype' field is empty, no messages seem to be generated by VALVE.

**Comment by lmcmicu** [comment]
It seems to be fine as long as the datatype has a parent whose description is not empty. For instance in valve's test data this is the case for the `label` datatype. It has no description but its parent, `trimmed line` has a description which is used for messages.

It also seems fine in the case where the datatype of the column has no description, but where the error message is not for a datatype error but something else (e.g., violation of a unique constraint).

The remaining case, which I think is the likely case where you are seeing this bug, is the case, specifically, of a datatype error for a datatype that has no description nor any parent that has a description. In valve's test data, the datatype `text` is an example.

**Comment by jamesaoverton** [comment]
Ok. Silently dropping messages is not good behaviour, so I see a few options:

1. make 'description' required
2. make a top-level description required
3. default to the name of the datatype if no description is provided

What do you think?

**Comment by lmcmicu** [comment]
Option 3 seems to me like the obvious choice. Further, the generated error message would look like: `"<column X> should be a <datatype name>"`, which to me sounds totally natural.
